Update readme
varvet/XibViewKit pull request #1
Opened 2018-05-03 12:47 UTC by cennydavidsson

2018-05-03 13:40 UTC, daniellAlgar requested changes

2018-05-03 13:40 UTC, daniellAlgar commented on README.md
> +You will new to create a .xib file with a view in it. Then select the file owner in the document outline.
- [ ] new --> need

2018-05-07 12:02 UTC, cennydavidsson commented
@daniellAlgar Approve?

2018-05-07 17:41 UTC, daniellAlgar approved these changes

2018-06-07 08:29 UTC, merged